apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondservice
  labels:
    app: secondservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: secondservice
  template:
    metadata:
      labels:
        app: secondservice
    spec:
      containers:
      - name: secondservice
        image: bhadrasayantan/secondservice:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /secondservice/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /secondservice/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
